# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13kkDYXQ1dBNQR8ccKe15NMnpcp7NlhXZ

Geovanna dos Santos Benedito
22502439
"""

import pandas as pd
import numpy as np

print('Hello, world')

name='geovanna'
age=18
weight=56

print(name,age,weight)
print(f'Olá {name}, você tem {age} anos e pesa {weight} kg')

# Lista de dados com nome, idade e peso
data_list= [name,age,weight]
print('O primeiro elemento da lista é:', data_list[0])
print('O segundo elemento da lista é:', data_list[1])

#alteração de valor na segunda posição
data_list[1]= 20

print(data_list)

# tupla de coordenadas no espaço
point=(1, -3)

#tuplas são imutáveis, levando ao erro
poit[1]=10

user={"name": "geovanna", "age": "18"}
print(user)

#acesso a valor de uma chave
print("O valor da chave 'name' é:",user["name"])
user['email']='geovanna@gmail.com'
print(user)

#expressão condicional
if int(user['age']) >= 18:
  print('Você pode ver o conteúdo')
else:
  print('Você não pode acessar esse conteúdo')

#loop
times = 1
while times < 10:
  print(f'Estou tentanto pela {times} vez')
  times += 1

#loop for: "para cada"
for number in [1,2,3,4]:
  print(f'Estou tentando pela {number} vez')

print('\n')
for number in range(1,5):
  print(f'Estou tentando pela {number} vez')

#exemplo tabuada
for number1 in range(1,10):
  for number2 in range(1,10):
    result= number1 * number2
    print(f'{number1} * {number2} =',{result})

#exemplo de um número elevado ao quadrado
for number1 in range(1,10):
    result= number1 ** 2
    print(f'{number1} ** 2 =',{result})

squares = []

for number1 in range(1,10):
    if is_odd(number1):
        result= number1 ** 2
        squares.append(result)

print(squares)

def square(number):
    return number ** 2

print(square(2))

def is_odd(number):
    return number % 2 != 0

print(is_odd(5))