# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r9r1QFONDO4FRxXcvOqLo8H0UlQh65gw

Geovanna dos Santos Benedito 22502439
"""

import time
import numpy as np

A = list(range(0,10_000))
B = list(range(10_001,20_001))

#tamanho
len(A)
len(B)

C = []
for idx in range(len(A)):
    C.append(A[idx] * B[idx])

#exibir os 5 primeiros elementos de c
print(C[:5])

start_time = time.time()

C = []
for i in range(len(A)):
    sum = 0
    for j in range(len(B)):
        sum += A[i] * B[j]

    C.append(sum)

print('Os 5 primeiros elementos de C:', C[:5])
print('Demorou:', time.time() - start_time, 'segundos')

A_np = np.array(A)
B_np = np.array(B)

start_time = time.time()

print(f"Shape de A: {A_np.shape}, B:{B_np.shape}, A.T: {A_np.shape}")
C_np = (A_np.T @ B_np).sum(axis=0)

print("Os 5 primeiros elemnentos de C:", C[:5])
print('Demorou:', time.time() - start_time, 'segundos')
print(f"Demorou {time.time() - start_time:.2f}s")

a = np.arange(1,1000)
print('Os 5 primeiros elementos de a:', a[:5])

#quadrado de ada elemnto de a
squares = a ** 2
print('Os 5 primeiros elemntos de de squares:', squares[:5])

is_greater_than_10 = squares > 10
print('Os 5 primeiros elementos de squares:', is_greater_than_10[:5])

values_greater_than_10 = squares [is_greater_than_10]
print('Os 5 primeiros elementos de values_greater_than_10:', values_greater_than_10[:5])

mean = squares.mean()
print('A média de squares é', f'{mean:,.2f}')

std = squares.std()
print('O desvio padrão de squares é', f'{std:,.2f}')

array_a = np.linspace(-1,1,num=10)
print('array_a:', array_a)

array_b = np.linspace(-2,2,num=10)
print('array_b:', array_b)

print('array a * b:', array_a * array_b)