# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nhTUpXDIkoZ3mGJl_X6Ql39zL37dW5qO

Geovanna dos Santos Benedito 22502439
"""

import pandas as pd

DATEBASE = '/content/drive/MyDrive/ml-100k/u.user'

df = pd.DataFrame({
    "name":["Geovanna", "Ana", "Sophia", "Bruno"],
    "age": [22, 26, 21, 18],
    "gender": ["fem", "fem", "fem","mas"],
    "score": ["SS", "MS", "MI", "SS"]
})
df

df["age"].mean()

#descrever dataframe
df.describe()

df["score"].value_counts()

def is_approved (score):
    if score in ["SS", "MS", "MM"]:
        return "Aprovado"
    else:
        return "Reprovado"

is_approved ("MI")

df["score"].apply(is_approved)

df["is_approved"] = df["score"].apply(is_approved)
df

df["is_approved"].value_counts()

df["is_approved"].value_counts() / len(df) * 100

df["is_approved"].value_counts().plot.pie()

df["is_approved"].value_counts().plot.bar(color=['purple', 'black'])

df_user = pd.read_csv(
    DATEBASE, sep="|",
    header = None,
    names=["user_id", "age", "gender", "occupation", "zip_code"])
df_user

#tarefa 1
df_user["gender"].value_counts() / len(df_user) * 100

#tarefa 2
df_user["occupation"].value_counts().plot.pie()

#tarefa 3
df_user["age"].min(), df_user["age"].max()