# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_c5WMDd-GwD6xquAcMK90Pl1eNecOFGH

Geovanna dos Santos Benedito
RA = 22502439
"""

import re

valid_email = 'nikson.ferrreira@ceub.edu.br'
invalid_email = 'niksonferrreiraceub.edu.br'

EMAIL_PATTERN = r"^[a-z.]*@[a-z.]*$"

re.search(EMAIL_PATTERN, valid_email)

re.search(EMAIL_PATTERN, invalid_email)

#Passo a passo
text = "aaa"
re.search(pattern='a+', string=text)

text = "ICDados"
re.search(pattern='a+', string=text)

text = "banananananana"
re.search(pattern='bana(na)+', string=text)

text = "123"
re.search(pattern='(123){2,3}', string=text)

text = "12"
re.search(pattern='123?', string=text)

text = """
Qual é seu telefone?
Meu telefone é 995472482
"""
re.search(pattern='[0-9]+', string=text)

text = """
Qual é seu CPF?
Meu CPF é 3456787764.106.177-19
"""
re.search(pattern=r'[0-9]{3}\.[0-9]{3}\.[0-9]{3}-[0-9]{2}', string=text)

text = """
Qual é seu CPF?
Meu CPF é 152.156.156-15
"""
re.search(pattern=r'\b\d{3}\.\d{3}\.\d{3}-\d{2}', string=text)

#Exercício 1 (apenas 1 digito)
text = "1"
re.search(pattern='^[0-9]$', string=text)

#Exercício 2 (5 digitos)
text = "23434"
re.search(pattern=r'^[0-9]{5}$', string=text)

#Exercício 3 (código postal)
text = "12.456-987"
re.search(pattern=r'\b\d{2}\.\d{3}\-\d{3}', string=text)

#Exercício 4 (código postal com ou sem hifen)
text = "75572414"
re.search(pattern=r'\b\d{2}(\.?)(\d{3})(-?\d{3})\b', string=text)

#Exercíco 5 (encrontrar link)
text = "https://www.name.com"
re.search(pattern=r'\b(?:https?://)?(?:www\.)?[\w-]+\.[a-z]{2,6}\b', string=text)

#Exercício 6 (cpf com ou sem  . e -)
text = "151215115145"
re.search(pattern=r'\b\d{3}(\.?)[\d]{3}(\.?)[\d]{3}(-?)[\d]{2}\b', string=text)

#Exercício 7 (e-mail)
text = "joe@aol.com"
re.search(pattern=r'^[a-z.]*@[a-z.]*$', string=text)

#Exercício 8 (datas)
text = "22/10/2006"
re.search(pattern=r'\b(?:\d{2}[-/.])?\d{2}[-/.]\d{2,4}\b', string=text)